Implemented ideas from https://serverfault.com/a/767079

diff --git a/media-automount b/media-automount
--- a/media-automount
+++ b/media-automount
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
-#$1 = <dev>
+
+# This script is called from our systemd unit file to mount or unmount
+# a USB drive.
 
 # Default options to use for mounting
 AUTOMOUNT_OPTS='noatime'
@@ -10,118 +12,154 @@ AUTOMOUNT_TYPE=''
 POST_MOUNT='/etc/post_mount/run.sh'
 
 # Directory to look for type-specific settings
-confdir=/etc/media-automount.d
+CONFDIR=/etc/media-automount.d
 
 # Directory to use as parent media dir for mountpoints
-mediadir=/media
+MEDIADIR=/media
 
-[[ $EUID != 0 ]] && {
-    echo "This tool requires root permissions"
-    exit 1
-}
+ACTION="$1"
+DEVBASE="$2"
+DEVICE="/dev/${DEVBASE}"
+
 shopt -s nullglob
 
-log() {
-    echo "media-automount" "$*"
+usage()
+{
+    echo "Usage (needs root permission): $0 {add|remove} device_name (e.g. sdb1)"
+    exit 1
 }
 
-if ! [ "$1" ]
-then
-    log "missing arguments! a device name must be provided"
-    exit 1
-else
-    dev=/dev/${1##*/}
-fi
+[[ $# -ne 2 ]] && {
+    usage
+}
 
-# Check if the device exists, if not but mounted, umount it
-if ! [ -b $dev ]
-then
-    if grep /etc/mtab -qe "^$dev"
+[[ $EUID != 0 ]] && {
+    usage
+}
+
+log() {
+    echo "$*"
+}
+
+do_unmount()
+{
+    # Check if $DEVICE is still mounted
+    if grep /etc/mtab -qe "^$DEVICE"
     then
-        log "$dev device removed, umounting and cleaning /media"
-        if umount "$dev"
+        log "Removed device $DEVICE, umounting..."
+        if umount "$DEVICE"
         then
             exitcode=0
         else
             exitcode=$?
-            log "Error umounting $dev errcode:$exitcode"
+            log "Error umounting $DEVICE errcode: $exitcode"
         fi
     else
         # prevent it from failing on nonexistent devices and degrading systemctl boot
         exitcode=0
-		log "device doesn't exist anymore or is not a block device: $dev"
+        log "Device doesn't exist anymore or is not a block device: $DEVICE"
     fi
 
-    # cleanup
-    for dir in "$mediadir"/*
-    do
-        [ -d "$dir" ] && ! mountpoint -q "$dir" && rmdir "$dir"
+    # Delete all empty dirs in $MEDIADIR that aren't being used as mount
+    # points. This is kind of overkill, but if the drive was unmounted
+    # prior to removal we no longer know its mount point, and we don't
+    # want to leave it orphaned...
+    for f in $MEDIADIR/* ; do
+        if [[ -n $(find "$f" -maxdepth 0 -type d -empty) ]]; then
+            if ! grep -q " $f " /etc/mtab; then
+                log "Removing mount point $f"
+                rmdir "$f"
+            fi
+        fi
     done
     exit $exitcode
-fi
+}
 
-# Load additional info for the block device
-eval $(blkid -po export $dev)
+do_mount()
+{
+    # Load additional info for the block device
+    eval $(blkid -po export $DEVICE)
 
-# Devices with unknown type will be ignored
-if [ -z "$TYPE" ]
-then
-    log "$dev has no known filesystem type, ignoring mount request"
-	exit 0
-fi
-
-# Don't attempt to mount zfs
-if [ "$TYPE" == "zfs_member" ]
-then
-    log "$dev filesystem type is $TYPE, ignoring mount request"
-	exit 0
-fi
-
-# Don't manage devices labelled EFI
-if [ "$LABEL" == "EFI" ]
-then
-    log "$dev has label $LABEL, automount won't manage it"
-    exit 0
-fi
-
-# Check /etc/fstab for an entry corresponding to the device
-[ "$UUID" ] && fstab=$(grep /etc/fstab -e "^[^#]*${UUID/\-/\\\-}") || \
-[ "$LABEL" ] && fstab=$(grep /etc/fstab -e "^[^#]*${LABEL/\-/\\\-}") || \
-fstab=$(grep /etc/fstab -e "^[ \t]*$dev[ \t]")
-
-# Don't manage devices that are already in fstab
-if [ "$fstab" ]
-then
-    log "$dev already in /etc/fstab, automount won't manage it: ${fstab/[ \t][ \t]/ }"
-    exit 0
-fi
-
-# directory name
-AUTOMOUNT_DIR="${mediadir}/${LABEL:-${dev##*/}}.$TYPE"
-
-# Load Filesystem-specific configuration for mounting
-if [ -e "$confdir/$TYPE" ]
-then
-	source "$confdir/$TYPE"
-fi
-
-log "mounting device $dev in $AUTOMOUNT_DIR"
-mkdir -p "$AUTOMOUNT_DIR"
-if mount ${AUTOMOUNT_TYPE:+-t $AUTOMOUNT_TYPE} ${AUTOMOUNT_OPTS:+-o $AUTOMOUNT_OPTS} $dev $AUTOMOUNT_DIR
-then
-    log "Device successfully mounted: $AUTOMOUNT_DIR"
-    
-    # Check if mount script exists
-    if [ -f "$POST_MOUNT" ]
+    # Devices with unknown type will be ignored
+    if [ -z "$TYPE" ]
     then
-        # Run mount script in background
-        "${POST_MOUNT}" "$AUTOMOUNT_DIR" "$dev" &
-        log "Running mount script in background"
+        log "$DEVICE has no known filesystem type, ignoring mount request"
+        exit 0
     fi
 
-    exit 0
-else
-    log "Mount error: $?"
-    rmdir "$AUTOMOUNT_DIR"
-    exit 1
-fi
+    # Don't attempt to mount zfs
+    if [ "$TYPE" == "zfs_member" ]
+    then
+        log "Device $DEVICE filesystem type is $TYPE, ignoring mount request"
+        exit 0
+    fi
+
+    # Don't manage devices labelled EFI
+    if [ "$LABEL" == "EFI" ]
+    then
+        log "Device $DEVICE has label $LABEL, automount won't manage it"
+        exit 0
+    fi
+
+    # Check /etc/fstab for an entry corresponding to the device
+    [ "$UUID" ] && fstab=$(grep /etc/fstab -e "^[^#]*${UUID/\-/\\\-}") || \
+    [ "$LABEL" ] && fstab=$(grep /etc/fstab -e "^[^#]*${LABEL/\-/\\\-}") || \
+    fstab=$(grep /etc/fstab -e "^[ \t]*$DEVICE[ \t]")
+
+    # Don't manage devices that are already in fstab
+    if [ "$fstab" ]
+    then
+        log "Device $DEVICE already in /etc/fstab, automount won't manage it: ${fstab/[ \t][ \t]/ }"
+        exit 0
+    fi
+
+    # Directory name
+    AUTOMOUNT_DIR="${MEDIADIR}/${LABEL:-${DEVICE##*/}}"
+
+    # Make unique mount point
+    if grep -q " ${AUTOMOUNT_DIR} " /etc/mtab; then
+        # Already in use, make a unique one
+        AUTOMOUNT_DIR+="-${DEVBASE}"
+    fi
+
+    # Load Filesystem-specific configuration for mounting
+    if [ -e "$CONFDIR/$TYPE" ]
+    then
+        source "$CONFDIR/$TYPE"
+    fi
+
+    log "Mounting device $DEVICE in $AUTOMOUNT_DIR"
+    mkdir -p "$AUTOMOUNT_DIR"
+    
+    # Don't include -t flag if AUTOMOUNT_TYPE is empty (same for -o and AUTOMOUNT_OPTS)
+    if mount ${AUTOMOUNT_TYPE:+-t $AUTOMOUNT_TYPE} ${AUTOMOUNT_OPTS:+-o $AUTOMOUNT_OPTS} $DEVICE $AUTOMOUNT_DIR
+    then
+        log "Device successfully mounted: $AUTOMOUNT_DIR"
+        
+        # Check if post mount script exists
+        if [ -f "$POST_MOUNT" ]
+        then
+            # Run post mount script in background
+            "${POST_MOUNT}" "$AUTOMOUNT_DIR" "$DEVICE" &
+            log "Running mount script in background"
+        fi
+
+        exit 0
+    else
+        log "Mount error: $?"
+        rmdir "$AUTOMOUNT_DIR"
+        exit 1
+    fi
+}
+
+case "${ACTION}" in
+    add)
+        do_mount
+        ;;
+    remove)
+        do_unmount
+        ;;
+    *)
+        usage
+        ;;
+esac
